#! /bin/bash
# Copyright © 2015 Michele Sorcinelli
#
# Author: Michele Sorcinelli <michelesr@autistici.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# database file path
DB_FILE='~/.cache/glocate.db'

# create aliases
alias updatedb="sudo find / | gzip > $DB_FILE"
alias locate="zcat $DB_FILE | grep "

# cleanup
unset DB_FILE
